placeholders:
    placeholders:
        segment_criteria_list:
            items:
                field_condition: ~
                segment_condition: ~

    items:
        field_condition:
            template: '@@OroSegment/Segment/field_condition.html.twig'
        segment_condition:
            template: '@@OroSegment/Segment/segment_condition.html.twig'
            applicable: "@oro_segment.placeholder.segment_condition_filter->isSegmentFilterShouldBeAdded()"
