api:
    entities:
        Oro\Bundle\OrganizationBundle\Entity\BusinessUnit:
            documentation_resource: '@OroOrganizationBundle/Resources/doc/api/business_unit.md'

        Oro\Bundle\OrganizationBundle\Entity\Organization:
            documentation_resource: '@OroOrganizationBundle/Resources/doc/api/organization.md'
            upsert: false
            actions:
                delete: false
                delete_list: false
                create: false
