oro_entity:
    entity_name_representation:
        Oro\Bundle\OrganizationBundle\Entity\Organization:
            full: [ name ]
            short: [ name ]
        Oro\Bundle\OrganizationBundle\Entity\BusinessUnit:
            full: [ name ]
            short: [ name ]

oro_query_designer:
    collapsed_associations:
        Oro\Bundle\OrganizationBundle\Entity\BusinessUnit:
            virtual_fields: [ id ]
            search_fields: [ name ]
