# * GET method: returns an entity of the given type by its identifier
# * DELETE method: deletes an entity of the given type by its identifier
# * PATCH method: updates the specified fields of the given entity
oro_rest_api_item:
    path: /api/{entity}/{id}
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: OroApiBundle:RestApi:item
    options:
        group: rest_api
        priority: -10

# * GET method: returns a list of entities of the given type
# * DELETE method: deletes a list of entities of the given type by the given filters
# * POST method: creates an entity of the given type
oro_rest_api_list:
    path: /api/{entity}
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: OroApiBundle:RestApi:list
    options:
        group: rest_api
        priority: -10

# * GET method: returns an entity (for to-one association)
#   or a list of entities (for to-many association)
#   connected to the given entity by the given association
oro_rest_api_subresource:
    path: /api/{entity}/{id}/{association}
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: OroApiBundle:RestApi:subresource
    options:
        group: rest_api
        priority: -10

# * GET method: returns an entity identifier (for to-one association)
#   or a list of entity identifiers (for to-many association)
#   connected to the given entity by the given association
# * PATCH method: updates a relationship between entities represented by the given association
#   for to-one association the target entity can be NULL to clear the association
#   for to-many association the existing relationships will be completely replaced with the specified list
# * POST method: adds the specified entities to the relationship represented by the given to-many association
# * DELETE method: deletes the specified entities from the relationship represented by the given to-many association
oro_rest_api_relationship:
    path: /api/{entity}/{id}/relationships/{association}
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: OroApiBundle:RestApi:relationship
    options:
        group: rest_api
        priority: -10


#
# deprecated routes with "_format" placeholder
# they are added to prevent BC break
# and they must be registered at the end to avoid collisions with main API routes
#

oro_rest_api_get_deprecated:
    path: /api/{entity}/{id}.{_format}
    methods: [GET]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/\.]+)
        _format: json
    defaults:
        _controller: OroApiBundle:RestApi:item
        _format: json
        _action: get
    options:
        group: rest_api_deprecated
        priority: -15

oro_rest_api_cget_deprecated:
    path: /api/{entity}.{_format}
    methods: [GET]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/\.]+)
        _format: json
    defaults:
        _controller: OroApiBundle:RestApi:list
        _format: json
        _action: get_list
    options:
        group: rest_api_deprecated
        priority: -15

oro_rest_api_delete_deprecated:
    path: /api/{entity}/{id}.{_format}
    methods: [DELETE]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: OroApiBundle:RestApi:item
        _format: json
        _action: delete
    options:
        group: rest_api_deprecated
        priority: -15

oro_rest_api_cdelete_deprecated:
    path: /api/{entity}.{_format}
    methods: [DELETE]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: OroApiBundle:RestApi:list
        _format: json
        _action: delete_list
    options:
        group: rest_api_deprecated
        priority: -15

oro_rest_api_post_deprecated:
    path: /api/{entity}.{_format}
    methods: [POST]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: OroApiBundle:RestApi:list
        _format: json
        _action: create
    options:
        group: rest_api_deprecated
        priority: -15

oro_rest_api_patch_deprecated:
    path: /api/{entity}/{id}.{_format}
    methods: [PATCH]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: OroApiBundle:RestApi:item
        _format: json
        _action: update
    options:
        group: rest_api_deprecated
        priority: -15

oro_rest_api_get_subresource_deprecated:
    path: /api/{entity}/{id}/{association}.{_format}
    methods: [GET]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: OroApiBundle:RestApi:subresource
        _format: json
        _action: get_subresource
    options:
        group: rest_api_deprecated
        priority: -15
