config:
    paths:
        'oroexpressionlanguage/lib/php-to-js/addcslashes': 'bundles/oroexpressionlanguage/lib/php-to-js/addcslashes.js'

        'oroexpressionlanguage/js/library/node/arguments-node': 'bundles/oroexpressionlanguage/js/library/node/arguments-node.js'
        'oroexpressionlanguage/js/library/node/array-node': 'bundles/oroexpressionlanguage/js/library/node/array-node.js'
        'oroexpressionlanguage/js/library/node/conditional-node': 'bundles/oroexpressionlanguage/js/library/node/conditional-node.js'
        'oroexpressionlanguage/js/library/node/constant-node': 'bundles/oroexpressionlanguage/js/library/node/constant-node.js'
        'oroexpressionlanguage/js/library/node/function-node': 'bundles/oroexpressionlanguage/js/library/node/function-node.js'
        'oroexpressionlanguage/js/library/node/name-node': 'bundles/oroexpressionlanguage/js/library/node/name-node.js'
        'oroexpressionlanguage/js/library/node/node': 'bundles/oroexpressionlanguage/js/library/node/node.js'
        'oroexpressionlanguage/js/library/node/unary-node': 'bundles/oroexpressionlanguage/js/library/node/unary-node.js'

        'oroexpressionlanguage/js/library/compiler': 'bundles/oroexpressionlanguage/js/library/compiler.js'
        'oroexpressionlanguage/js/library/expression-syntax-error': 'bundles/oroexpressionlanguage/js/library/expression-syntax-error.js'
