security:
    firewalls:
        wsse_secured:
            pattern: ^/api/rest.*
            provider: oro_user
            stateless:  true
            wsse:
                lifetime: 3600
                realm:    "Secured API"
                profile:  "UsernameToken"
            entry_point: wsse
            context: main
            organization-remember-me: # should be the same as for "main" firewall except "csrf_protected_mode" option
                token_provider:             oro_security.token.provider.rememberme
                secret:                     '%kernel.secret%'
                name:                       BAPRM
                lifetime:                   1209600   # stay logged for two weeks
                httponly:                   true
                csrf_protected_mode:        true
            custom_authenticator: oro_user.impersonation_authenticator
