acls:
    oro_translation_language_create:
        type: entity
        permission: CREATE
        class: Oro\Bundle\TranslationBundle\Entity\Language

    oro_translation_language_view:
        type: entity
        permission: VIEW
        class: Oro\Bundle\TranslationBundle\Entity\Language

    oro_translation_language_update:
        type: entity
        permission: EDIT
        class: Oro\Bundle\TranslationBundle\Entity\Language

    oro_translation_language_translate:
        type: entity
        permission: TRANSLATE
        class: Oro\Bundle\TranslationBundle\Entity\Language
