security:
    firewalls:
        embedded_form:
            pattern: ^/embedded-form/(submit|success)
            provider: chain_provider

oro_security:
    access_control:
        - { path: ^%web_backend_prefix%/embedded-form/(submit|success), roles: PUBLIC_ACCESS }
