services:
    oro_locale.cache:
        parent: oro.data.cache
        tags:
            - { name: 'cache.pool', namespace: 'oro_locale' }

    oro_locale.cache.provider.tree_fallback_strategy:
        parent: oro.data.cache
        public: false
        tags:
            - { name: 'cache.pool', namespace: 'oro_locale_tree_fallback_strategy' }

    oro_locale.cache.manager:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter
        shared: false
        arguments:
            - '%oro_cache.data_adapter_lifetime%'
            - false

    oro_locale.localization.localization_provider.cache.warmer:
        class: Oro\Component\Config\Cache\ConfigCacheWarmer
        public: false
        arguments:
            - '@oro_locale.manager.localization'
        tags:
            - { name: kernel.cache_warmer }
