services:
    _defaults:
        tags:
            - { name: oro_message_queue.topic }

    Oro\Bundle\DataGridBundle\Async\Topic\DatagridPreExportTopic:
        arguments:
            - '%oro_datagrid.export.size_of_batch%'
            - '@oro_security.token_accessor'
        calls:
            - [ 'setConfigurationProvider', ['@oro_datagrid.configuration.provider.chain'] ]

    Oro\Bundle\DataGridBundle\Async\Topic\DatagridExportTopic:
        calls:
            - [ 'setConfigurationProvider', ['@oro_datagrid.configuration.provider.chain'] ]
