services:
    oro_dataaudit.tests.migration_listener:
        class: Oro\Bundle\DataAuditBundle\Tests\Functional\Environment\TestEntitiesMigrationListener
        tags:
            - { name: kernel.event_listener, event: oro_migration.post_up, method: onPostUp }

    oro_dataaudit.tests.entity_class_name_provider:
        class: Oro\Bundle\DataAuditBundle\Tests\Functional\Environment\StubEntityClassNameProvider
        tags:
            - { name: oro_entity.class_name_provider, priority: 255 }

    Oro\Bundle\DataAuditBundle\EventListener\DataFixturesExecutingListener:
        arguments:
            - '@oro_platform.optional_listeners.manager'
            - '@oro_distribution.handler.application_status'
        tags:
            - { name: kernel.event_listener, event: oro_migration.data_fixtures.pre_load, method: onPreLoad }
            - { name: kernel.event_listener, event: oro_migration.data_fixtures.post_load, method: onPostLoad }

    oro_dataaudit.tests.entity_name_resolver.classes_provider:
        class: Oro\Bundle\DataAuditBundle\Tests\Functional\Environment\TestEntityNameResolverClassesProvider
        decorates: oro_entity.tests.entity_name_resolver.classes_provider
        arguments:
            - '@.inner'
            - '@oro_entity_config.config_manager'
            - '@doctrine'
