services:
    oro_integration.transport.rest.client_factory.stub:
        decorates: oro_integration.transport.rest.client_factory
        class: 'Oro\Bundle\IntegrationBundle\Test\FakeRestClientFactory'
        public: true

    oro_integration.connector.test_connector:
        class: Oro\Bundle\IntegrationBundle\Test\Provider\TestConnector
        arguments:
            - '@oro_importexport.context_registry'
            - '@oro_integration.logger.strategy'
            - '@oro_integration.provider.connector_context_mediator'
        tags:
            - { name: oro_integration.connector, type: connector1, channel_type: foo }

    oro_integration.sync_scheduler:
        class: Oro\Bundle\IntegrationBundle\Manager\SyncScheduler
        public: true
        arguments:
            - '@oro_message_queue.message_producer'

    oro_integration.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\IntegrationBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
