doctrine:
    orm:
        entity_managers:
            config:
                mappings:
                    OroEntityConfigBundle:
                        mapping:   true
                        is_bundle: true

oro_message_queue:
    persistent_services:
        - 'oro_entity_config.cache'

oro_entity:
    entity_name_representation:
        Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeFamily:
            short: [ code ]
