config:
    paths:
        'oroquerydesigner/js/app/views/condition-builder/condition-builder-view': 'bundles/oroquerydesigner/js/app/views/condition-builder/condition-builder-view.js'
        'oroquerydesigner/js/app/views/abstract-condition-view': 'bundles/oroquerydesigner/js/app/views/abstract-condition-view.js'
        'oroquerydesigner/js/app/views/field-condition-view': 'bundles/oroquerydesigner/js/app/views/field-condition-view.js'
        'oroquerydesigner/js/app/views/column-form-view': 'bundles/oroquerydesigner/js/app/views/column-form-view.js'
        'oroquerydesigner/js/app/views/aggregated-field-condition-view': 'bundles/oroquerydesigner/js/app/views/aggregated-field-condition-view.js'
        'oroquerydesigner/js/app/views/function-choice-view': 'bundles/oroquerydesigner/js/app/views/function-choice-view.js'
        'oroquerydesigner/js/app/models/grouping-model': 'bundles/oroquerydesigner/js/app/models/grouping-model.js'
        'oroquerydesigner/js/app/models/column-model': 'bundles/oroquerydesigner/js/app/models/column-model.js'
        'oroquerydesigner/js/app/models/entity-field-model': 'bundles/oroquerydesigner/js/app/models/entity-field-model.js'
        'oroquerydesigner/js/app/models/entity-fields-collection': 'bundles/oroquerydesigner/js/app/models/entity-fields-collection.js'

        'oroquerydesigner/js/app/components/condition-builder-component': 'bundles/oroquerydesigner/js/app/components/condition-builder-component.js'
        'oroquerydesigner/js/app/components/query-type-converter-component': 'bundles/oroquerydesigner/js/app/components/query-type-converter-component.js'
        'oroquerydesigner/js/app/views/date-grouping-view': 'bundles/oroquerydesigner/js/app/views/date-grouping-view.js'

        'oroquerydesigner/js/enum-filter-initialized': 'bundles/oroquerydesigner/js/enum-filter-initialized.js'

        'oroquerydesigner/js/app/modules/validator-constraints-module': 'bundles/oroquerydesigner/js/app/modules/validator-constraints-module.js'
        'oroquerydesigner/js/app/modules/entity-filter-preset-module': 'bundles/oroquerydesigner/js/app/modules/entity-filter-preset-module.js'
        'oroquerydesigner/js/validator/not-blank-filters': 'bundles/oroquerydesigner/js/validator/not-blank-filters.js'

        'oroquerydesigner/js/query-type-converter/from-expression/abstract-filter-translator': 'bundles/oroquerydesigner/js/query-type-converter/from-expression/abstract-filter-translator.js'
        'oroquerydesigner/js/query-type-converter/from-expression/dictionary-filter-translator': 'bundles/oroquerydesigner/js/query-type-converter/from-expression/dictionary-filter-translator.js'
        'oroquerydesigner/js/query-type-converter/from-expression/field-id-translator': 'bundles/oroquerydesigner/js/query-type-converter/from-expression/field-id-translator.js'
        'oroquerydesigner/js/query-type-converter/to-expression/abstract-filter-translator': 'bundles/oroquerydesigner/js/query-type-converter/to-expression/abstract-filter-translator.js'
        'oroquerydesigner/js/query-type-converter/to-expression/dictionary-filter-translator': 'bundles/oroquerydesigner/js/query-type-converter/to-expression/dictionary-filter-translator.js'
        'oroquerydesigner/js/query-type-converter/to-expression/string-filter-translator': 'bundles/oroquerydesigner/js/query-type-converter/to-expression/string-filter-translator.js'
        'oroquerydesigner/js/query-type-converter/to-expression/field-id-translator': 'bundles/oroquerydesigner/js/query-type-converter/to-expression/field-id-translator.js'
        'oroquerydesigner/js/query-type-converter/expression-functions-provider': 'bundles/oroquerydesigner/js/query-type-converter/expression-functions-provider.js'

    appmodules:
        - oroquerydesigner/js/app/modules/validator-constraints-module
        - oroquerydesigner/js/app/modules/entity-filter-preset-module
