services:
    _defaults:
        public: true

    Oro\Bundle\EntityBundle\Controller\DictionaryController:
        arguments:
            - '@oro_entity.dictionary_entity_data_provider'

    Oro\Bundle\EntityBundle\Controller\EntitiesController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_entity_config.provider.entity }
            - { name: container.service_subscriber, id: oro_entity_config.provider.extend }
