services:
    _defaults:
        public: true

    Oro\Bundle\DigitalAssetBundle\Controller\DigitalAssetController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_attachment.provider.attachment_entity_config, key: Oro\Bundle\AttachmentBundle\Provider\AttachmentEntityConfigProviderInterface }
