services:
    _defaults:
        public: false

    Oro\Bundle\EntityConfigBundle\Command\CacheClearCommand:
        arguments:
            - '@oro_entity_config.config_manager'
            - '@oro_entity_config.config_cache_warmer'
        tags:
            - { name: console.command }

    Oro\Bundle\EntityConfigBundle\Command\CacheWarmupCommand:
        arguments:
            - '@oro_entity_config.config_cache_warmer'
        tags:
            - { name: console.command }

    Oro\Bundle\EntityConfigBundle\Command\DebugCommand:
        arguments:
            - '@doctrine'
            - '@oro_entity_config.config_manager'
        tags:
            - { name: console.command }

    Oro\Bundle\EntityConfigBundle\Command\UpdateCommand:
        arguments:
            - '@Oro\Bundle\EntityConfigBundle\Tools\ConfigLoader'
        tags:
            - { name: console.command }

    Oro\Bundle\EntityConfigBundle\Command\OroEntityConfigDumpReferenceCommand:
        arguments:
            - '@oro_entity_config.configuration_handler'
        tags:
            - { name: console.command }
