services:
    oro_report.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\ReportBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
