services:
    _defaults:
        public: false

    Oro\Bundle\ThemeBundle\Command\ThemeCommand:
        public: false
        class: Oro\Bundle\ThemeBundle\Command\ThemeCommand
        arguments:
            - '@oro_theme.registry'
        tags:
            - { name: console.command }

    Oro\Bundle\ThemeBundle\Command\ThemeValidateConfigurationCommand:
        public: false
        class: Oro\Bundle\ThemeBundle\Command\ThemeValidateConfigurationCommand
        arguments:
            - '@oro_theme.chain_configuration_validator'
        tags:
            - { name: console.command }
