services:
    oro_theme.fallback.provider.theme_configuration_provider:
        class: Oro\Bundle\ThemeBundle\Fallback\Provider\ThemeConfigurationFallbackProvider
        parent: oro_entity.fallback.provider.abstract_provider
        arguments:
            - '@oro_theme.provider.theme_configuration'
        tags:
            - { name: oro_entity.fallback_provider, id: themeConfiguration, priority: 20 }
