services:
  ### FORM TYPES ###
  oro_theme.form.type.configuration:
      class: Oro\Bundle\ThemeBundle\Form\Type\ThemeConfigurationType
      arguments:
          - '@oro_theme.form.subscriber.theme_configuration'
      tags:
          - { name: form.type, alias: oro_theme_configuration }

  oro_theme.form.type.configuration_children:
      class: Oro\Bundle\ThemeBundle\Form\Type\ConfigurationType
      arguments:
          - '@oro_theme.form.configuration_child_provider'
      tags:
          - { name: form.type, alias: oro_theme_configuration_children }

  oro_theme.form.type.theme_configuration_select:
      class: Oro\Bundle\ThemeBundle\Form\Type\ThemeConfigurationSelectType
      tags:
          - { name: form.type, alias: oro_theme_configuration_select }

  ### CONFIGURATION CHILDREN BUILDER ###
  _instanceof:
      Oro\Bundle\ThemeBundle\Form\Configuration\ConfigurationChildBuilderInterface:
          tags: ['oro_theme.form.configuration_child_builder']

  oro_theme.form.select_option_builder:
      class: Oro\Bundle\ThemeBundle\Form\Configuration\SelectBuilder
      arguments:
          - '@assets.packages'

  oro_theme.form.radio_option_builder:
      class: Oro\Bundle\ThemeBundle\Form\Configuration\RadioBuilder
      arguments:
          - '@assets.packages'

  oro_theme.form.checkbox_option_builder:
      class: Oro\Bundle\ThemeBundle\Form\Configuration\CheckboxBuilder
      arguments:
          - '@assets.packages'

  oro_theme.form.menu_choice_builder:
      class: Oro\Bundle\ThemeBundle\Form\Configuration\MenuChoiceBuilder
      arguments:
          - '@assets.packages'

  oro_theme.form.configuration_child_provider:
      class: Oro\Bundle\ThemeBundle\Form\Provider\ConfigurationBuildersProvider
      arguments:
          - !tagged_iterator oro_theme.form.configuration_child_builder

  ### SUBSCRIBERS ###
  oro_theme.form.subscriber.theme_configuration:
      class: Oro\Bundle\ThemeBundle\Form\EventListener\ThemeConfigurationSubscriber
      arguments:
          - '@oro_layout.theme_extension.configuration.provider'

  ### FORM HANDLERS ###
  oro_theme.form.handler.theme_configuration:
      class: Oro\Bundle\ThemeBundle\Form\Handler\ThemeConfigurationHandler
      arguments:
          - '@doctrine'
      tags:
          - { name: oro_form.form.handler, alias: oro_theme.form.handler.theme_configuration }
