services:
    oro_theme.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\ThemeBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
