acls:
    oro_note_view:
        type: entity
        class: Oro\Bundle\NoteBundle\Entity\Note
        permission: VIEW
        group_name: ""
        bindings: ~

    oro_note_create:
        type: entity
        class: Oro\Bundle\NoteBundle\Entity\Note
        permission: CREATE
        group_name: ""
        bindings: ~

    oro_note_update:
        type: entity
        class: Oro\Bundle\NoteBundle\Entity\Note
        permission: EDIT
        group_name: ""
        bindings: ~

    oro_note_delete:
        type: entity
        class: Oro\Bundle\NoteBundle\Entity\Note
        permission: DELETE
        group_name: ""
        bindings: ~
