oro_api:
    error_title_overrides:
        'email address constraint': 'email constraint'
        'not empty email template translation subject constraint': 'not blank constraint'
    form_types:
        - Oro\Bundle\EmailBundle\Api\Form\Type\EmailAddressType
        - Oro\Bundle\EmailBundle\Api\Form\Type\EmailFolderType

oro_entity:
    entity_name_representation:
        Oro\Bundle\EmailBundle\Entity\Email:
            full: [ subject ]
            short: [ subject ]
