oro_sanitize:
    entity:
        akeneo_batch_job_execution: truncate_cascade
        akeneo_batch_job_instance: truncate_cascade
        akeneo_batch_step_execution: truncate_cascade
        akeneo_batch_warning: truncate
