services:
  oro_test.artifacts.runtime_subscriber:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Artifacts\RunTimeSubscriber
    arguments:
      - '@event_dispatcher'
      - '@oro_test.artifacts.progress_artifacts_subscriber'
      - '@oro_test.artifacts.pretty_artifacts_subscriber'
    tags:
      - { name: event_dispatcher.subscriber, priority: 10 }

  oro_test.artifacts.screenshot_generator:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Artifacts\ScreenshotGenerator
    arguments:
      - '@mink'
      - !abstract '$handlers defined in Oro\Bundle\TestFrameworkBundle\Behat\ServiceContainer\OroTestFrameworkExtension'

  oro_test.artifacts.pretty_artifacts_subscriber:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Artifacts\PrettyArtifactsSubscriber
    arguments:
      - '@output.formatter.pretty'
      - '@oro_test.artifacts.screenshot_generator'
      - '@mink'

  oro_test.artifacts.failed_feature_subscriber:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Artifacts\FailedFeaturesSubscriber
    arguments:
    - '@oro_test.storage.failed_features'
    tags:
    - { name: event_dispatcher.subscriber }

  oro_test.artifacts.progress_artifacts_subscriber:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Artifacts\ProgressArtifactsSubscriber
    arguments:
      - '@output.progress.statistics'
      - '@output.formatter.progress'
      - '@oro_test.artifacts.screenshot_generator'

  oro_test.artifacts.ftp_handler:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Artifacts\FtpHandler
    arguments:
      - []
    tags:
      - { name: 'artifacts_handler' }

  oro_test.artifacts.local_handler:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Artifacts\LocalHandler
    arguments:
      - []
    tags:
      - { name: 'artifacts_handler' }
