api:
    entity_aliases:
        Extend\Entity\EV_Auth_Status:
            alias: userauthstatus
            plural_alias: userauthstatuses
        Oro\Bundle\UserBundle\Api\Model\UserProfile:
            alias: userprofile
            plural_alias: userprofile

    entities:
        Oro\Bundle\UserBundle\Entity\Group:
            documentation_resource: '@OroUserBundle/Resources/doc/api/group.md'

        Oro\Bundle\UserBundle\Entity\Role:
            documentation_resource: '@OroUserBundle/Resources/doc/api/role.md'
            upsert: false
            actions:
                update:
                    fields:
                        role:
                            form_options:
                                constraints:
                                    - NotBlank: ~

        Oro\Bundle\UserBundle\Entity\User:
            documentation_resource: '@OroUserBundle/Resources/doc/api/user.md'
            fields:
                emails:
                    data_type: objects
                    exclusion_policy: all
                    fields:
                        email: ~
                emailLowercase:
                    exclude: true
                usernameLowercase:
                    exclude: true
                passwordChangedAt:
                    form_options:
                        mapped: false
                passwordRequestedAt:
                    form_options:
                        mapped: false
                loginCount:
                    form_options:
                        mapped: false
                lastLogin:
                    form_options:
                        mapped: false
                emailOrigins:
                    exclude: true
            actions:
                create:
                    fields:
                        password:
                            exclude: false # set manually because this field is excluded globally
                            form_options:
                                property_path: plainPassword

        Extend\Entity\EV_Auth_Status:
            documentation_resource: '@OroUserBundle/Resources/doc/api/user.md'

        Oro\Bundle\UserBundle\Entity\Email:
            # this entity does not have own API resource
            actions: false

        Oro\Bundle\UserBundle\Api\Model\UserProfile:
            documentation_resource: '@OroUserBundle/Resources/doc/api/user_profile.md'
            actions:
                get:
                    description: Get current logged in user
                get_list: false
                create: false
                update: false
                delete: false
                delete_list: false
                get_subresource: false
                get_relationship: false
                update_relationship: false
                add_relationship: false
                delete_relationship: false
